SELECT 'PROD_LI.' ||
       'COMMON_DATA.' ||
       'SALES_ORDERS' AS "record source"
     , DB                         AS "database"
     , ICM_ID                     AS "icm id"
     , VBAP_POSNR                 AS "document line number"
     , ICM_CUSTOMER_ID            AS "entity icm id"
     , 'Customer'                 AS "entity title"
     , VBAK_KUNNR                 AS "entity number"
     , VBAK_KUNNR_KNA1_NAME1      AS "entity name"
     , VBAK_VBTYP                 AS "document category code"
     , "VBAK_VBTYP_Concat"        AS "document category"
     , VBAK_AUART                 AS "document type code"
     , "VBAK_AUART_Concat"        AS "document type"
     , VBAP_ERDAT                 AS "creation date"
     , VBAP_ERNAM                 AS "created by"
     , VBAK_AUDAT                 AS "document date"
     , VBAP_NETWR_USD             AS "document value"
     , VBAK_WAERK                 AS "document currency"
     , "VBAP_KWMENG_Base"         AS "document quantity"
     , VBAP_ARKTX                 AS "document text"
     , VBAP_MATKL                 AS "material group code"
     , "VBAP_MATKL_Concat"        AS "material group"
     , VBAP_MATNR                 AS "material code"
     , "VBAP_MATNR_Concat"        AS "material"
     , VBAK_BUKRS_VF              AS "company code id"
     , "VBAK_BUKRS_VF_Concat"     AS "company code"
     , VBAP_PRCTR_ORG1            AS "organization, level 1 code"
     , "VBAP_PRCTR_ORG1_Concat"   AS "organization, level 1"
     , VBAP_PRCTR_ORG2            AS "organization, level 2 code"
     , "VBAP_PRCTR_ORG2_Concat"   AS "organization, level 2"
     , VBAP_PRCTR_ORG3            AS "organization, level 3 code"
     , "VBAP_PRCTR_ORG3_Concat"   AS "organization, level 3"
     , NULL                       AS "deletion indicator"
  FROM PROD_LI.COMMON_DATA.SALES_ORDERS