SELECT DB                       AS "database"
     , ICM_ID                   AS "document id"
     , VBRP_POSNR               AS "document line number"
     , VBRK_BUKRS               AS "company code id"
     , "VBRK_BUKRS_Concat"      AS "company code"
     , VBRK_FKTYP               AS "document category code"
     , "VBRK_FKTYP_Concat"      AS "document category"
     , VBRK_FKART               AS "document type code"
     , "VBRK_FKART_Concat"      AS "document type"
     , NULL                     AS "deletion indicator"
     , VBRK_ERDAT               AS "creation date"
     , VBRK_ERNAM               AS "created by"
     , 'Customer'               AS "entity type"
     , ICM_SOLD_TO_ID           AS "entity icm id"
     , VBRK_KUNAG               AS "entity number"
     , "VBRK_KUNAG_Concat"      AS "entity"
     , VBRK_FKDAT               AS "document date"
     , VBRP_ARKTX               AS "document text"
     , VBRK_WAERK               AS "document currency"
     , VBRP_NETWR_USD           AS "document value"
     , "VBRP_FKIMG_Base"        AS "document quantity"
     , VBRP_MATNR               AS "material code"
     , "VBRP_MATNR_Concat"      AS "material"
     , VBRP_MATKL               AS "material group code"
     , "VBRP_MATKL_Concat"      AS "material group"
     , VBRP_PRCTR_ORG1          AS "organization, level 1 code"
     , "VBRP_PRCTR_ORG1_Concat" AS "organization, level 1"
     , VBRP_PRCTR_ORG2          AS "organization, level 2 code"
     , "VBRP_PRCTR_ORG2_Concat" AS "organization, level 2"
     , VBRP_PRCTR_ORG3          AS "organization, level 3 code"
     , "VBRP_PRCTR_ORG3_Concat" AS "organization, level 3"
  FROM PROD_LI.COMMON_DATA.BILLING_DOCS