SELECT DB                       AS "database"
     , ICM_ID                   AS "document id"
     , NULL                     AS "document line number"
     , NULL                     AS "company code id"
     , NULL                     AS "company code"
     , NULL                     AS "document category code"
     , 'Master Record'          AS "document category"
     , 'KNA1'                   AS "document type code"
     , 'Customer Master Record' AS "document type"
     , NULL                     AS "deletion indicator"
     , KNA1_ERDAT               AS "creation date"
     , KNA1_ERNAM               AS "created by"
     , 'Customer'               AS "entity type"
     , ICM_ID                   AS "entity icm id"
     , KNA1_KUNNR               AS "entity number"
     , "KNA1_KUNNR_Concat"      AS "entity"
     , CURRENT_DATE()           AS "document date"
     , CONCAT_WS(' ',
                 KNA1_NAME1,
                 KNA1_NAME2,
                 KNA1_NAME3,
                 KNA1_NAME4)    AS "document text"
     , NULL                     AS "document currency"
     , NULL                     AS "document value"
     , NULL                     AS "document quantity"
     , NULL                     AS "material code"
     , NULL                     AS "material"
     , NULL                     AS "material group code"
     , NULL                     AS "material group"
     , NULL                     AS "organization, level 1 code"
     , NULL                     AS "organization, level 1"
     , NULL                     AS "organization, level 2 code"
     , NULL                     AS "organization, level 2"
     , NULL                     AS "organization, level 3 code"
     , NULL                     AS "organization, level 3"
  FROM PROD_LI.COMMON_DATA.CENTRAL_CUSTOMER_MASTER