SELECT DB                         AS "database"
     , ICM_ID                     AS "document id"
     , EKPO_EBELP                 AS "document line number"
     , EKKO_BUKRS                 AS "company code id"
     , "EKKO_BUKRS_Concat"        AS "company code"
     , EKKO_BSTYP                 AS "document category code"
     , "EKKO_BSTYP_Concat"        AS "document category"
     , EKKO_BSART                 AS "document type code"
     , "EKKO_BSART_Concat"        AS "document type"
     , EKKO_LOEKZ                 AS "deletion indicator"
     , EKKN_AEDAT                 AS "creation date"
     , EKKO_ERNAM                 AS "created by"
     , 'Vendor'                   AS "entity type"
     , ICM_VENDOR_ID              AS "entity icm id"
     , EKKO_LIFNR                 AS "entity number"
     , "EKKO_LIFNR_Concat"        AS "entity"
     , EKKO_BEDAT                 AS "document date"
     , EKPO_TXZ01                 AS "document text"
     , EKKO_WAERS                 AS "document currency"
     , "EKKN_Value_USD"           AS "document value"
     , EKET_MENGE                 AS "document quantity"
     , EKPO_MATNR                 AS "material code"
     , "EKPO_MATNR_Concat"        AS "material"
     , EKPO_MATKL                 AS "material group code"
     , "EKPO_MATKL_Concat"        AS "material group"
     , "ProfitCenter_ORG1"        AS "organization, level 1 code"
     , "ProfitCenter_ORG1_Concat" AS "organization, level 1"
     , "ProfitCenter_ORG2"        AS "organization, level 2 code"
     , "ProfitCenter_ORG2_Concat" AS "organization, level 2"
     , "ProfitCenter_ORG3"        AS "organization, level 3 code"
     , "ProfitCenter_ORG3_Concat" AS "organization, level 3"
  FROM PROD_LI.COMMON_DATA.PURCHASE_ORDERS