SELECT 'PROD_LI.' ||
       'COMMON_DATA.' ||
       'BILLING_DOCS'              AS "record source"
     , DB                          AS "database"
     , ICM_ID || '|' || VBRP_POSNR AS "id"
     , ICM_ID                      AS "icm id"
     , VBRP_POSNR                  AS "document line number"
     , ICM_SOLD_TO_ID              AS "entity icm id"
     , 'Customer'                  AS "entity title"
     , VBRK_KUNAG                  AS "entity number"
     , "VBRK_KUNAG_Concat"         AS "entity name"
     , VBRK_FKTYP                  AS "document category code"
     , "VBRK_FKTYP_Concat"         AS "document category"
     , VBRK_FKART                  AS "document type code"
     , "VBRK_FKART_Concat"         AS "document type"
     , VBRK_ERDAT                  AS "creation date"
     , VBRK_ERNAM                  AS "created by"
     , VBRK_FKDAT                  AS "document date"
     , VBRP_NETWR_USD              AS "document value"
     , VBRK_WAERK                  AS "document currency"
     , "VBRP_FKIMG_Base"           AS "document quantity"
     , VBRP_ARKTX                  AS "document text"
     , VBRP_MATKL                  AS "material group code"
     , "VBRP_MATKL_Concat"         AS "material group"
     , VBRP_MATNR                  AS "material code"
     , "VBRP_MATNR_Concat"         AS "material"
     , VBRK_BUKRS                  AS "company code id"
     , "VBRK_BUKRS_Concat"         AS "company code"
     , VBRP_PRCTR_ORG1             AS "organization, level 1 code"
     , "VBRP_PRCTR_ORG1_Concat"    AS "organization, level 1"
     , VBRP_PRCTR_ORG2             AS "organization, level 2 code"
     , "VBRP_PRCTR_ORG2_Concat"    AS "organization, level 2"
     , VBRP_PRCTR_ORG3             AS "organization, level 3 code"
     , "VBRP_PRCTR_ORG3_Concat"    AS "organization, level 3"
     , NULL                        AS "deletion indicator"
  FROM PROD_LI.COMMON_DATA.BILLING_DOCS