SELECT DB                     AS "database"
     , ICM_ID                 AS "document id"
     , NULL                   AS "document line number"
     , PROJ_VBUKR             AS "company code id"
     , NULL                   AS "company code"
     , NULL                   AS "document category code"
     , NULL                   AS "document category"
     , 'PROJ'                 AS "document type code"
     , 'Project Definition'   AS "document type"
     , NULL                   AS "deletion indicator"
     , PROJ_ERDAT             AS "creation date"
     , PROJ_ERNAM             AS "created by"
     , NULL                   AS "entity type"
     , NULL                   AS "entity icm id"
     , NULL                   AS "entity number"
     , NULL                   AS "entity"
     , PROJ_PLFAZ             AS "document date"
     , PROJ_POST1             AS "document text"
     , NULL                   AS "document currency"
     , NULL                   AS "document value"
     , NULL                   AS "document quantity"
     , NULL                   AS "material code"
     , NULL                   AS "material"
     , NULL                   AS "material group code"
     , NULL                   AS "material group"
     , PROJ_PRCTR_ORG1        AS "organization, level 1 code"
     , PROJ_PRCTR_ORG1_CONCAT AS "organization, level 1"
     , PROJ_PRCTR_ORG2        AS "organization, level 2 code"
     , PROJ_PRCTR_ORG2_CONCAT AS "organization, level 2"
     , PROJ_PRCTR_ORG3        AS "organization, level 3 code"
     , PROJ_PRCTR_ORG3_CONCAT AS "organization, level 3"
  FROM COMMON_DATA.PROJECTS